DROP TABLE customer_contact;
DROP TABLE invoice;
DROP TABLE Reservation;
DROP TABLE Today_Price;
DROP TABLE Customer;
DROP TABLE Employee_phno;
DROP TABLE Rooms;
DROP TABLE Employee;
DROP TABLE Hotel;